# Generated by Django 4.1.4 on 2024-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_to_apply', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('alternate_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('tenth_percentage', models.CharField(max_length=10)),
                ('twelfth_percentage', models.CharField(max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
